###############################################################################
#                               Districts

###
#@name create_district
POST http://0.0.0.0:5000/district
content-type: application/json
Authorization: {{token}}

{
  "name": "Some string",
  "address": "Some string",
  "city": {"id":  "UUID as string"},
  "archdiocese": {"id":  "UUID as string"}
}

###
#@name alter_district
PUT http://0.0.0.0:5000/district/<string:district_id>
content-type: application/json
Authorization: {{token}}

{
  "name": "Some string",
  "address": "Some string",
  "city": {"id":  "UUID as string"},
  "archdiocese": {"id":  "UUID as string"}
}

###
#@name district_inactivate
DELETE http://0.0.0.0:5000/district/<string:district_id>
content-type: application/json
Authorization: {{token}}

###
#@name district_activate
POST http://0.0.0.0:5000/district/activate
content-type: application/json
Authorization: {{token}}

{
  "id": "UUID as string"
}

###
#@name get_one_district
GET http://0.0.0.1:5000/district/<string:district_id>
content-type: application/json
Authorization: {{token}}


###
#@name district_autocomplete
POST http://0.0.0.0:5000/district/autocomplete
content-type: application/json
Authorization: {{token}}

{
  "search": "Some string"
}


###
#@name district_search
POST http://0.0.0.0:5000/district/search
content-type: application/json
Authorization: {{token}}

{
  "search": "Some string"
}

###
#@name get_districts
GET http://0.0.0.1:5000/district?start=some_int&limit=some_int&district_name=some_string&address=some_string&city_id=some_string&archdiocese_id=some_string
content-type: application/json
Authorization: {{token}}