###############################################################################
#                               Cities

###
#@name create_city
POST http://0.0.0.0:5000/city
content-type: application/json
Authorization: {{token}}

{
  "name": "Some string",
  "state": {"id":  "UUID as string"}
}

###
#@name alter_city
PUT http://0.0.0.0:5000/city/<string:city_id>
content-type: application/json
Authorization: {{token}}

{
  "name": "Some string",
  "state": {"id":  "UUID as string"}
}

###
#@name city_inactivate
DELETE http://0.0.0.0:5000/city/<string:city_id>
content-type: application/json
Authorization: {{token}}

###
#@name city_activate
POST http://0.0.0.0:5000/city/activate
content-type: application/json
Authorization: {{token}}

{
  "id": "UUID as string"
}

###
#@name get_one_city
GET http://0.0.0.1:5000/city/<string:city_id>
content-type: application/json
Authorization: {{token}}


###
#@name city_autocomplete
POST http://0.0.0.0:5000/city/autocomplete
content-type: application/json
Authorization: {{token}}

{
  "search": "Some string"
}


###

#@name city_search
POST http://0.0.0.0:5000/city/search
content-type: application/json
Authorization: {{token}}

{
  "search": "Some string"
}

###
#@name get_cities
GET http://0.0.0.1:5000/city?start=some_int&limit=some_int&city_name=some_string&state_id=some_string
content-type: application/json
Authorization: {{token}}