"""changes in persons_history

Revision ID: 00049659fbd6
Revises: 09b6eb3edc7b
Create Date: 2020-06-23 10:13:36.615071

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '00049659fbd6'
down_revision = '09b6eb3edc7b'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('persons_history', sa.Column('birth_place', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, 'persons_history', 'cities', ['birth_place'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'persons_history', type_='foreignkey')
    op.drop_column('persons_history', 'birth_place')
    # ### end Alembic commands ###
