"""registry_of_marriages and person_extra_info

Revision ID: 36de5edd0f5c
Revises: 29b7164424dd
Create Date: 2020-06-16 10:39:29.206100

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '36de5edd0f5c'
down_revision = '29b7164424dd'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person_extra_info',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('person_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('baptism_district', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('baptism_date', sa.Date(), nullable=True),
    sa.Column('parents_canonically_married', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('status', sa.SmallInteger(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['baptism_district'], ['districts.id'], ),
    sa.ForeignKeyConstraint(['parents_canonically_married'], ['list_items.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('registry_of_marriages',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('person_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('person2_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('best_man', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('best_man2', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('status', sa.SmallInteger(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['best_man'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['best_man2'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['person2_id'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('registry_of_marriages')
    op.drop_table('person_extra_info')
    # ### end Alembic commands ###
