"""domicile added

Revision ID: 50ecc36e70d2
Revises: fc40a04ac397
Create Date: 2020-05-27 11:39:36.053198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50ecc36e70d2'
down_revision = 'fc40a04ac397'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
