"""note model

Revision ID: 6dbcba7d7b9f
Revises: ad8cb8c19035
Create Date: 2020-06-03 09:39:12.380240

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6dbcba7d7b9f'
down_revision = 'ad8cb8c19035'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notes',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('person_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('chrism_place', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('chrism_date', sa.Date(), nullable=True),
    sa.Column('marriage_district', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('marriage_date', sa.Date(), nullable=True),
    sa.Column('spouse_name', sa.String(length=255), nullable=True),
    sa.Column('other_notes', sa.Text(), nullable=True),
    sa.Column('status', sa.SmallInteger(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chrism_place'], ['cities.id'], ),
    sa.ForeignKeyConstraint(['marriage_district'], ['districts.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notes')
    # ### end Alembic commands ###
