"""new_column added

Revision ID: 9afc0721171c
Revises: 6dbcba7d7b9f
Create Date: 2020-06-03 13:45:42.169823

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9afc0721171c'
down_revision = '6dbcba7d7b9f'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registry_of_baptisms', sa.Column('parents_canonically_married', postgresql.UUID(as_uuid=True), nullable=False))
    op.create_foreign_key(None, 'registry_of_baptisms', 'list_items', ['parents_canonically_married'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'registry_of_baptisms', type_='foreignkey')
    op.drop_column('registry_of_baptisms', 'parents_canonically_married')
    # ### end Alembic commands ###
