"""title and auxiliary_description added

Revision ID: b74162a563a8
Revises: bb6a37a26a69
Create Date: 2020-06-10 10:30:31.650224

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b74162a563a8'
down_revision = 'bb6a37a26a69'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('list_items', sa.Column('auxiliary_description', postgresql.UUID(as_uuid=True), nullable=True))
    op.add_column('users', sa.Column('title', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'title')
    op.drop_column('list_items', 'auxiliary_description')
    # ### end Alembic commands ###
