###############################################################################
#                               Users

###
#@name create_user
POST http://0.0.0.0:5000/user
content-type: application/json
Authorization: {{token}}

{
  "first_name": "Some string",
  "last_name": "Some string",
  "username": "Some string",
  "email": "Some string",
  "role": {"id":  "UUID as string"},
  "district": {"id":  "UUID as string"}
}


###
#@name get_one_user
GET http://0.0.0.1:5000/user/<string:user_id>
content-type: application/json
Authorization: {{token}}


###
#@name user_autocomplete
POST http://0.0.0.0:5000/user/autocomplete
content-type: application/json
Authorization: {{token}}

{
  "search": "Some string"
}


###
#@name get_users
GET http://0.0.0.1:5000/user?start=some_int&limit=some_int&first_name=some_string&last_name=some_string&username=some_string&email=some_string&role_id=some_string&district_id=some_string
content-type: application/json
Authorization: {{token}}